/**
 *
 * @format
 * @flow
 * */
export const TERA_WALLET_GENERATE_NEW_KEY_BEGIN = 'TERA_WALLET_GENERATE_NEW_KEY_BEGIN';
export const TERA_WALLET_GENERATE_NEW_KEY_SUCCESS = 'TERA_WALLET_GENERATE_NEW_KEY_SUCCESS';
export const TERA_WALLET_GENERATE_NEW_KEY_FAILED = 'TERA_WALLET_GENERATE_NEW_KEY_FAILED';

export const generateKeyPairs = () => ({
  type: TERA_WALLET_GENERATE_NEW_KEY_BEGIN,
});
